'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NestedMasterPage2

    '''<summary>
    '''namaSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents namaSubMenu As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSubMenu As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hidSubMenu2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSubMenu2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''FormContents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormContents As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
